---
title: "Projekt"
subtitle: "Technologie webowe"
author:
  - Krzysztof Mizgała, album 262839
date: "2024-12-20"
lang: pl
mainfont: Latin Modern Roman
sansfont: Latin Modern Roman
fontsize: 12pt
format:
  pdf:
    toc: true
    colorlinks: true
    fig-pos: H
execute: 
  enabled: true
  cache: true
---

```{python}
#| label: setup
#| include: false
import numpy as np
import pandas as pd
import matplotlib as mpl
from matplotlib import pyplot as plt
from scraper import Scraper, read_games
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.preprocessing import MultiLabelBinarizer
from keras.models import Sequential
from keras.layers import Dense, Dropout
from tabulate import tabulate
from IPython.display import Markdown, display
def print_table(table, headers='firstrow', **kwargs):
  display(Markdown(tabulate(table, headers=headers, **kwargs)))

mpl.rcParams['font.family'] = 'serif'
mpl.rcParams['font.serif'] = ['Latin Modern Roman', 'Times New Roman', 'serif']
mpl.rcParams['font.size'] = 12
mpl.rcParams['axes.spines.top'] = False
mpl.rcParams['axes.spines.right'] = False
mpl.rcParams['axes.titlesize'] = 16
mpl.rcParams['axes.titlepad'] = 4
mpl.rcParams['axes.titleweight'] = 400
mpl.rcParams['figure.dpi'] = 100
mpl.rcParams['figure.figsize'] = (8, 6)
```
\newpage

# Wprowadzenie

## Cel projektu

Projekt polega na scrapowaniu danych o grach planszowych z serwisu [BoardGameGeek](https://boardgamegeek.com/) oraz analizie tych danych. Dane są pobierane za pomocą skryptu w Pythonie, który wykorzystuje bibliotekę Selenium do nawigacji po stronie internetowej i pobierania informacji o grach. Zebrane dane są następnie analizowane przy użyciu różnych technik analizy danych i uczenia maszynowego.

## Czym jest scrapowanie danych?

Scrapowanie danych, znane również jako web scraping, to proces automatycznego pobierania informacji ze stron internetowych. Wykorzystuje się do tego specjalne skrypty lub narzędzia, które nawigują po stronach, pobierają zawartość i przetwarzają ją w celu uzyskania potrzebnych danych. Scrapowanie danych jest szczególnie przydatne, gdy dane nie są dostępne w formie łatwo dostępnych plików do pobrania, ale są wyświetlane na stronach internetowych.

## Dlaczego BoardGameGeek.com?

BoardGameGeek.com (BGG) jest jednym z najbardziej znanych i szanowanych serwisów internetowych poświęconych grom planszowym. Strona ta jest szeroko uznawana za jedno z głównych źródeł informacji o grach planszowych, zarówno wśród graczy, jak i&nbsp;wydawców oraz projektantów gier. Dzięki swojej popularności, BGG gromadzi ogromną ilość danych na temat gier planszowych, co czyni go idealnym źródłem do analizy.

## Struktura projektu

- `scraper.py`: Skrypt do scrapowania danych z BoardGameGeek.
- `projekt.ipynb`: Notebook Jupyter zawierający kod do analizy danych.
- `games.csv`: Plik CSV zawierający zebrane dane o grach planszowych.
- `raport.pdf`: Raport końcowy w formacie PDF.

# Scrapowanie danych

## Przygotowanie środowiska

Aby rozpocząć proces scrapowania danych, należy spełnić następujące wymagania:

1. **Python 3.11**: Upewnij się, że masz zainstalowaną wersję Python 3.11.
2. **Google Chrome**: Zainstaluj przeglądarkę Google Chrome.
3. **ChromeDriver**: Pobierz [ChromeDriver](https://googlechromelabs.github.io/chrome-for-testing/#stable) i umieść go w katalogu zawierającym plik `scraper.py` lub dodaj jego lokalizację do zmiennej środowiskowej `PATH`.
4. **Biblioteki Python**: Zainstaluj wymagane biblioteki, wykonując poniższe polecenie:
   
   ```sh
   pip install -r requirements.txt
   ```
5. **Utwórz plik `.env`**: Utwórz plik `.env` w katalogu projektu i dodaj do niego swoje dane logowania do BoardGameGeek:
   
   ```sh
   USER='twoja_nazwa_uzytkownika'
   PASS='twoje_haslo'
   ```

## Uruchomienie scrapera

Aby uruchomić scraper i pobrać dane o grach planszowych, wykonaj poniższe polecenie w terminalu:
```sh
python scraper.py
```

Scraper posiada również następujące opcje wiersza poleceń (flagi):

- `-g` lub `--games`: liczba gier do pobrania (domyślnie 10000)
- `-c` lub `--checkpoint`: zapisuj dane co określoną liczbę gier (domyślnie 100)
- `-f` lub `--filename`: nazwa pliku do zapisu danych (domyślnie `games.csv`)

Na przykład, aby pobrać dane o 5000 grach, zapisywać dane co 50 gier w pliku `my_games.csv`:
```sh
python scraper.py -g 5000 -c 50 -f my_games.csv
```

## Proces scrapowania

### Logowanie do serwisu

- Skrypt `scraper.py` inicjalizuje obiekt klasy `Scraper`, który konfiguruje przeglądarkę Chrome w trybie headless (bez interfejsu graficznego).
- Po wejściu na stronę scraper automatycznie akceptuje pliki cookie.
- Scraper otwiera panel logowania BoardGameGeek. Logowanie jest konieczne, aby uzyskać pełen dostęp do danych.
- Logowanie odbywa się za pomocą danych użytkownika (nazwa użytkownika i hasło) pobranych z pliku `.env`.
- Selenium symuluje wypełnienie pól logowania oraz kliknięcie przycisku ,,Zaloguj".

### Pobieranie linków

Metoda `get_links` pobiera linki do stron z grami planszowymi.
Na każdej podstronie rankingu wyświetlane jest 100 gier.
W celu uzyskania wystarczającego zbioru danych do analizy, pobieramy dane ze 100 stron, co daje nam zbiór 10 tys. gier.
Domyślnie gry są posortowane według oceny, zatem sortujemy je po liczbie ocen malejąco, aby uzyskać jak najbardziej wiarygodne wyniki.

Odwiedzamy kolejne strony rankingu, używając adresów URL zawierających numer strony.
Linki są zapisywane w pliku `links.txt`, aby uniknąć ponownego pobierania w przypadku przerwania procesu.

### Pobieranie danych o grach

Metoda `get_games` iteruje przez pobrane linki i dla każdej gry pobiera szczegółowe informacje. Dla każdej gry wykonano następujące kroki:

- Odwiedzano zakładkę z danymi statystycznymi (`/stats`) na stronie szczegółowej gry.
- Pobierano informacje o grze, w tym:
  - **Podstawowe dane**: nazwa gry, rok wydania, liczba graczy, czas rozgrywki, wymagany wiek, złożoność gry i alternatywne nazwy gry (jeśli istnieją).
  - **Opinie**: liczba ocen, średnia ocena, odchylenie standardowe oraz dokładny rozkład ocen w skali od 1 do 10.
  - **Statystyki**: liczba komentarzy, fanów, wyświetleń strony, liczba rozgrywek (ogółem i w bieżącym miesiącu).
  - **Informacje o posiadaniu**: liczba osób posiadających grę, liczba chętnych na zakup lub wymianę.
  - **Osoby zaangażowane**: projektanci, artyści i wydawcy.
- Wszystkie te informacje były wyodrębniane przy użyciu odpowiednich selektorów CSS i metod Selenium (`find_element` lub `find_elements`).
- Dane są zapisywane w formie słownika i dodawane do listy gier.
- W przypadku brakujących danych, skrypt zapisuje wartość `None`. Dodatkowa metoda `fill_missing` umożliwia ponowne odwiedzenie stron gier z brakującymi danymi w celu ich uzupełnienia (jeśli brak danych wynikał z błędu ładowania strony).

### Zabezpieczenia i optymalizacja

- W przypadku problemów z ładowaniem strony (np. pusta strona lub opóźnienia serwera), skrypt wykonuje wielokrotne próby ponownego załadowania strony.
- Dla zabezpieczenia danych postęp scrapowania jest zapisywany regularnie, co umożliwia wznowienie pracy od ostatniego zarejestrowanego punktu kontrolnego.
- W celu zmniejszenia ryzyka blokady przez serwer BoardGameGeek, wprowadzono losowe opóźnienia między zapytaniami (od 2 do 10 sekund).

### Zapisywanie danych

Dane są zapisywane w pliku `games.csv` co określoną liczbę gier (domyślnie co 100 gier), aby zapewnić bezpieczeństwo danych w przypadku przerwania procesu.
Format CSV pozwala na łatwe wczytanie danych do analizy przy użyciu biblioteki `pandas`.

### Zakończenie

Po zakończeniu procesu scrapowania, przeglądarka Chrome jest zamykana, a dane są gotowe do analizy.

# Analiza danych

Strona BoardGameGeek ma 10-stopniową skalę oceniania gier planszowych.
Gry oceniane są od 1 do 10, gdzie 1 oznacza najgorszą ocenę, a 10 najlepszą.

Zbadamy cechy gier, które mają wpływ na ich lepszą ocenę oraz cechy, które wpływają na największą spójność ocen (czyli czy gra jest oceniana podobnie przez różnych użytkowników).
W następnej sekcji spróbujemy także stworzyć modele predykcyjne, które będą przewidywać jak może być oceniana gra na podstawie jej cech.

## Struktura danych

Pierwszym krokiem analizy jest wczytanie danych z pliku `games.csv`, uzyskanego w&nbsp;wyniku scrapowania.

```{python}
#| label: load-data
df = read_games()
df.shape
```

Mamy przygotowane dane 10 tys. wierszy i 36 kolumn, z których 6 to zmienne kategoryczne, a 30 to kolumny z danymi liczbowymi. Zebrane dane zawierają następujące kolumny:

1. Podstawowe informacje:
   - Nazwa (name)
   - Rok wydania (year)
   - Opis (description)
   - Wymagana liczba graczy (min_players, max_players)
   - Czas gry (min_playtime, max_playtime)
   - Wymagany wiek (min_age)
   - Złożoność gry (complexity)
   - Alternatywne nazwy (alternate_names)
   - Projektanci (designers)
   - Artyści (artists)
   - Wydawcy (publishers)

2. Opinie:
   - Liczba ocen (ratings)
   - Średnia ocena (avg_rating)
   - Odchylenie standardowe (std_rating)
   - Rozkład ocen (ratings_1, ratings_2, ..., ratings_10)

3. Statystyki gry:
   - Liczba komentarzy (comments)
   - Liczba fanów (fans)
   - Wyświetlenia strony (page_views)

4. Statystyki rozgrywek:
   - Liczba rozgrywek (plays)
   - Liczba rozgrywek w tym miesiącu (plays_month)

5. Dane na temat posiadania gry:
   - Liczba osób posiadających grę (owners)
   - Liczba osób, które posiadały grę (prev_owned)
   - Liczba osób, które chcą sprzedać grę (for_trade)
   - Liczba osób, które chcą kupić grę (want_in_trade)
   - Liczba osób, które mają grę na liście życzeń (wishlist)

## Czyszczenie i przetwarzanie danych

Usuwamy kolumnę `description` ponieważ nie wykorzystujemy jej w analizie.
```{python}
#| label: clean-data-1
df = df.drop(columns=['description'])
```

Usuwamy wiersze z brakującymi danymi.
```{python}
#| label: clean-data-2
df = df.dropna()
```

Konwertujemy zmienne na odpowiednie typy danych.
```{python}
#| label: clean-data-3
#| echo: false
cols_float = ['complexity', 'avg_rating', 'std_rating']
cols_int = ['year', 'min_players', 'max_players', 'min_play_time', 'max_play_time',
            'min_age', 'ratings', 'ratings_1', 'ratings_2', 'ratings_3', 'ratings_4',
            'ratings_5', 'ratings_6', 'ratings_7', 'ratings_8', 'ratings_9',
            'ratings_10', 'comments', 'fans', 'page_views', 'plays', 'plays_month',
            'owners', 'prev_owned', 'for_trade', 'want_in_trade', 'wishlist']
cols_list = ['alternate_names', 'designers', 'artists', 'publishers']
```
```{python}
#| label: clean-data-4
df[cols_float] = df[cols_float].astype(np.float32)
df[cols_int] = df[cols_int].astype(np.int32)
df[cols_list] = df[cols_list].map(lambda x: [i.strip(',') for i in x])
```

## Analiza statystyk opisowych

```{python}
#| label: numerical-stats
#| tbl-cap: Statystyki opisowe dla zmiennych liczbowych
#| echo: false
print_table(df.describe().T[['mean', 'std', 'min', '25%', '50%', '75%', 'max']], headers='keys')
```

- Średnia liczba ocen to około 2702, co wskazuje na dużą popularność gier.
- Średnia ocena to 6.97, co sugeruje, że większość gier jest dobrze oceniana.
- Wartości `year` mogą być ujemne (min: -3500), co oznacza wydanie gry przed naszą erą, uwzględnimy to podczas dalszej analizy.

Sprawdzimy jakie są najczęściej występujące wartości w kolumnach z danymi kategorycznymi.
```{python}
#| label: categorical-stats-1
#| tbl-cap: Najczęściej występujący projektanci gier planszowych
#| echo: false
# zwracamy uwagę na to, że każda kolumna z listą zawiera więcej niż jedną wartość
print_table(df['designers'].explode().value_counts().head(10).reset_index().values, headers=['Projektant', 'Liczba gier'])
```

Wiele gier ma nieznanego projektanta, są to głównie starsze gry, dla których trudno jest znaleźć dokładne informacje.

```{python}
#| label: categorical-stats-2
#| tbl-cap: Najczęściej występujący artyści gier planszowych
#| echo: false
print_table(df['artists'].explode().value_counts().head(10).reset_index().values, headers=['Artysta', 'Liczba gier'])
```
```{python}
#| label: categorical-stats-3
#| tbl-cap: Najczęściej występujący wydawcy gier planszowych
#| echo: false
print_table(df['publishers'].explode().value_counts().head(10).reset_index().values, headers=['Wydawca', 'Liczba gier'])
```

Wśród wydawców wyróżnia się Fantasy Flight Games, co nie jest zaskoczeniem, biorąc pod uwagę popularność ich gier.

## Analiza eksploracyjna

```{python}
#| label: ratings-distribution
#| fig-cap: Rozkład ocen gier planszowych
#| echo: false
ratings = [f'ratings_{i}' for i in range(1, 11)]
ratings = df[ratings].sum()

plt.bar(list(range(1, 11)), ratings)
plt.xlabel('Ocena')
plt.ylabel('Liczba ocen')
plt.title('Rozkład ocen gier planszowych')
plt.show()
```

- Najwięcej ocen znajduje się w przedziale 7-8. Oznacza to, że gry planszowe są najczęściej oceniane jako dobre lub bardzo dobre.
- Liczba ocen gwałtownie spada w skrajnych przedziałach. Sugeruje to, że gry planszowe rzadko otrzymują skrajnie niskie lub skrajnie wysokie oceny.
- Rozkład ocen nie jest symetryczny. Może to sugerować, że oceniający są bardziej skłonni do dawania ocen w górnym zakresie skali, ale nie najwyższych możliwych ocen.

```{python}
#| label: correlation-matrix
#| fig-cap: Macierz korelacji między zmiennymi numerycznymi
#| echo: false
corr = df.select_dtypes(include='number').corr()
plt.matshow(corr)
plt.xticks(range(len(corr)), corr.columns)
plt.yticks(range(len(corr)), corr.columns)
plt.colorbar()
plt.title('Korelacje między zmiennymi numerycznymi')
plt.xticks(rotation=90)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.show()
```

Zwróćmy szczególną uwagę na korelacje zmiennej `avg_rating` z innymi zmiennymi.
Najbardziej skorelowana jest zmienna `complexity`, co sugeruje, że złożoność gry ma wpływ na jej ocenę.

Odchylenie standardowe `std_rating` nie wykazuje silnych korelacji z innymi zmiennymi, co sugeruje, że różnorodność ocen nie jest silnie związana z innymi cechami gry.

```{python}
#| label: top-games
#| tbl-cap: Najczęściej oceniane gry planszowe i ich oceny
#| echo: false
top_games = df[['name', 'avg_rating', 'ratings']].sort_values('ratings', ascending=False).head(10)
print_table(top_games.values, headers=['Gra', 'Średnia ocena', 'Liczba ocen'])
```

Najpopularniejsze gry planszowe mają bardzo wysokie oceny, wskazując na ich wysoką jakość w oczach graczy.

```{python}
#| label: top-designers
#| tbl-cap: Najlepsi projektanci gier planszowych według średniej oceny
#| echo: false
top_designers = df.explode('designers').groupby('designers')['avg_rating'].mean().sort_values(ascending=False).head(10)
print_table(top_designers.reset_index().values, headers=['Projektant', 'Średnia ocena'])
```

Najlepsi projektanci gier planszowych według średniej oceny to głównie znani i cenieni twórcy.

Pokażemy kilka interesujących zależności między zmiennymi:
```{python}
#| label: complexity-vs-rating
#| fig-cap: Złożoność w stosunku do średniej oceny
#| echo: false
plt.scatter(df['complexity'], df['avg_rating'], alpha=0.6)
plt.title("Średnia ocena vs Złożoność")
plt.xlabel("Złożoność")
plt.ylabel("Średnia ocena")
plt.show()
```

Jak wcześniej sugerowała macierz korelacji, złożoność gry ma wpływ na jej ocenę.
Widać tendencję, że gry o większej złożoności są lepiej oceniane.

```{python}
#| label: fans-vs-rating
#| fig-cap: Liczba fanów w stosunku do średniej oceny
#| echo: false
plt.scatter(df['fans'], df['avg_rating'], alpha=0.6)
plt.title("Średnia ocena vs Liczba fanów")
plt.xlabel("Liczba fanów")
plt.ylabel("Średnia ocena")
plt.show()
```

Słabo oceniane gry mają bardzo małą liczbę fanów. Gry z dużą liczbą fanów są zazwyczaj dobrze oceniane.

```{python}
#| label: min-players-vs-rating
#| fig-cap: Minimalna liczba graczy w stosunku do średniej oceny
#| echo: false
grouped_data = [df[df['min_players'] == i]['avg_rating'].values
                for i in sorted(df['min_players'].unique())]
plt.violinplot(grouped_data, showmeans=True)
plt.title("Średnia ocena vs Minimalna liczba graczy")
plt.xlabel("Minimalna liczba graczy")
plt.ylabel("Średnia ocena")
plt.show()
```

Jeśli minimalna liczba graczy jest większa niż 4 to jest praktycznie pewne, że gra będzie dobrze oceniana.

Z drugiej strony lepiej oceniane są średnio gry, w które można samemu, niż te, które wymagają większej liczby graczy.

```{python}
#| label: avg-rating-by-year
#| fig-cap: Średnia ocena gier planszowych na przestrzeni lat (od 1900 roku)
#| echo: false
df.groupby('year')['avg_rating'].mean().plot(kind='line', color='red')
plt.title("Średnia ocena na przestrzeni lat")
plt.xlabel("Rok wydania")
plt.ylabel("Średnia ocena")
plt.xlim(1900, 2024)
plt.show()
```

Na wykresie pokazujemy jedynie gry wydane po 1900 roku, gdyż jest bardzo mało gier z&nbsp;wcześniejszych lat.
Widać, że w ostatnich latach gry planszowe są coraz lepiej oceniane, co może świadczyć o postępie w tej dziedzinie.

```{python}
#| label: avg-rating-by-designer
#| fig-cap: Średnia ocena gier planszowych według projektantów
#| echo: false
top_designers = df['designers'].explode().value_counts().head(20).index
df_designers = df.explode('designers')
df_designers = df_designers[df_designers['designers'].isin(top_designers)]
df_designers.groupby('designers')['avg_rating'].mean().sort_values().plot(kind='barh')
plt.title("Średnia ocena gier według projektantów")
plt.xlabel("Średnia ocena")
plt.ylabel("Projektant")
plt.show()
```

Dla 20 najpopularniejszych projektantów gier planszowych, widać znaczące różnice w&nbsp;ocenach ich gier. Szczególnie widać, że słabo oceniane są gry z nieznanym projektantem.

## Wnioski

Rynek gier planszowych dynamicznie się rozwija, co widać po wysokich ocenach i rosnącej popularności. Większość gier jest dobrze oceniana, z dominującym przedziałem 7-8, a bardziej złożone tytuły cieszą się szczególnym uznaniem. Najlepsze gry wyróżniają się wysoką jakością, a kluczową rolę odgrywają uznani wydawcy, tacy jak Fantasy Flight Games, oraz cenieni projektanci.

Ostatnie lata przyniosły wzrost jakości nowych gier, co pokazuje innowacyjność i rozwój branży. Zaangażowanie społeczności graczy potwierdza znaczenie gier planszowych jako popularnego i stale rosnącego medium rozrywkowego.

# Modelowanie predykcyjne

W przypadku predykcji oceny gry, nie będziemy korzystać z żadnej ze zmiennych związanych z ocenami, aby uniknąć tzw. ,,data leakage" (wycieku danych).

## Przygotowanie danych

W celu przygotowania danych do modelowania, dzielimy zbiór danych na zbiór treningowy i testowy w stosunku 80:20. Następnie wybieramy zbiór cech, które będą wykorzystane do predykcji oceny gry.

```{python}
#| label: prepare-data
#| echo: false
columns = ['min_players', 'max_players', 'min_play_time', 'max_play_time', 'min_age', 'complexity',
           'comments', 'fans', 'page_views', 'plays', 'plays_month', 'owners', 'prev_owned',
           'for_trade', 'want_in_trade', 'wishlist', 'avg_rating', 'std_rating']

# Z powodu wielu rzadko występujących wartości, bierzemy 50, 15, 5 i 5
# najczęstszych wartości dla projektantów, artystów i wydawców
# dla pozostałych wartości ustawiamy 'inne'
top_values = {
    'designers': df['designers'].explode().value_counts().nlargest(50).index,
    'artists': df['artists'].explode().value_counts().nlargest(15).index,
    'publishers': df['publishers'].explode().value_counts().nlargest(5).index
}
for column, top in top_values.items():
    df[column] = df[column].apply(lambda x: [column+' '+i if i in top else 'other_'+column for i in x])

mlb = MultiLabelBinarizer()
for column in top_values.keys():
    df = df.join(pd.DataFrame(mlb.fit_transform(df[column]), columns=mlb.classes_, index=df.index))
df = df.drop(columns=['designers', 'artists', 'publishers'])


X = df.drop(columns=['ratings_1', 'ratings_2', 'ratings_3', 'ratings_4', 'ratings_5',
                     'ratings_6', 'ratings_7', 'ratings_8', 'ratings_9', 'ratings_10',
                     'avg_rating', 'std_rating', 'name', 'alternate_names'])
y = df[['avg_rating', 'std_rating']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=314)
mse = {}
```

## Regresja liniowa

Pierwszym modelem, który zastosujemy, jest regresja liniowa. Regresja liniowa jest jednym z najprostszych modeli regresji, który zakłada liniową zależność między zmiennymi niezależnymi a zmienną zależną.

```{python}
#| label: linear-regression
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
```

### Ocena modelu

```{python}
#| label: linear-regression-evaluation
#| tbl-cap: Ocena modelu regresji liniowej
#| echo: false
mse_avg = mean_squared_error(y_test['avg_rating'], y_pred[:, 0])
mse_std = mean_squared_error(y_test['std_rating'], y_pred[:, 1])
mse['lr'] = (mse_avg, mse_std)
print_table([['Metryka', 'Średni błąd kwadratowy'],
             ['Średnia ocena', mse_avg],
             ['Odchylenie standardowe ocen', mse_std]])
```

Regresja liniowa zakłada prostą, liniową relację między cechami a wynikami, co może prowadzić do niedoszacowania lub przeszacowania wpływu niektórych cech, szczególnie gdy dane mają charakter nieliniowy.

### Ważność cech

```{python}
#| label: linear-regression-feature-importance-1
#| fig-cap: Ważność cech w modelu regresji liniowej dla średniej oceny
#| echo: false
feature_importance = model.coef_[0]
feature_names = X_train.columns
for column in ['designers', 'artists', 'publishers']:
    indices = [i for i, feature in enumerate(feature_names) if feature.startswith(column)]
    importance = feature_importance[indices].sum()
    feature_importance = np.delete(feature_importance, indices)
    feature_importance = np.append(feature_importance, importance)
    feature_names = np.delete(feature_names, indices)
    feature_names = np.append(feature_names, column)
feature_importance = np.abs(feature_importance)
feature_importance = feature_importance / feature_importance.sum()
sort = np.argsort(feature_importance)
plt.barh(feature_names[sort], feature_importance[sort])
plt.xlabel('Ważność cech')
plt.title('Ważność cech w modelu regresji liniowej dla średniej oceny')
plt.gcf().set_figheight(3.5)
plt.show()
```

```{python}
#| label: linear-regression-feature-importance-2
#| fig-cap: Ważność cech w modelu regresji liniowej dla odchylenia standardowego ocen
#| echo: false
feature_importance = model.coef_[1]
feature_names = X_train.columns
for column in ['designers', 'artists', 'publishers']:
    indices = [i for i, feature in enumerate(feature_names) if feature.startswith(column)]
    importance = feature_importance[indices].sum()
    feature_importance = np.delete(feature_importance, indices)
    feature_importance = np.append(feature_importance, importance)
    feature_names = np.delete(feature_names, indices)
    feature_names = np.append(feature_names, column)
feature_importance = np.abs(feature_importance)
feature_importance = feature_importance / feature_importance.sum()
sort = np.argsort(feature_importance)
plt.barh(feature_names[sort], feature_importance[sort])
plt.xlabel('Ważność cech')
plt.title('Ważność cech w modelu regresji liniowej dla odchylenia standardowego ocen')
plt.gcf().set_figheight(3.5)
plt.show()
```

### Wnioski

- Zarówno średnia ocena, jak i odchylenie standardowe ocen są w dużej mierze kształtowane przez cechy związane z twórcami gry (projektanci, artyści, wydawcy). Sugeruje to, że renoma i liczba osób zaangażowanych w tworzenie gry mają kluczowe znaczenie.
- Złożoność gry jest istotnym czynnikiem dla średniej oceny, ale mniej wpływa na zróżnicowanie ocen. Gry o większej głębi mogą być bardziej doceniane, ale niekoniecznie wywołują większe kontrowersje wśród graczy.
- Statystyki dotyczące liczby rozgrywek, komentarzy czy wyświetleń strony mają marginalny wpływ, co może wskazywać, że czynniki związane z jakością gry są ważniejsze niż jej popularność.
- Parametry związane z wymianą i handlem grami mają zauważalny wpływ, co może być interesującą wskazówką dla twórców i wydawców, że popyt na rynku wtórnym może korelować z ocenami gry.

## Gradient Boosting

Kolejnym modelem, który zastosujemy, jest Gradient Boosting. Gradient Boosting to technika uczenia maszynowego, która polega na łączeniu wielu słabych modeli predykcyjnych w celu uzyskania silnego modelu.

```{python}
#| label: gradient-boosting
model = MultiOutputRegressor(GradientBoostingRegressor(random_state=314))
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
```

### Ocena modelu

```{python}
#| label: gradient-boosting-evaluation
#| tbl-cap: Ocena modelu Gradient Boosting
#| echo: false
mse_avg = mean_squared_error(y_test['avg_rating'], y_pred[:, 0])
mse_std = mean_squared_error(y_test['std_rating'], y_pred[:, 1])
mse['gb'] = (mse_avg, mse_std)
print_table([['Metryka', 'Średni błąd kwadratowy'],
             ['Średnia ocena', mse_avg],
             ['Odchylenie standardowe ocen', mse_std]])
```

Model Gradient Boosting osiągnął znacznie niższy błąd, co wskazuje na lepszą zdolność przewidywania średniej oceny gry. Wynika to z elastyczności GB, który lepiej uwzględnia nieliniowe zależności i interakcje między cechami.

### Ważność cech

```{python}
#| label: gradient-boosting-feature-importance-1
#| fig-cap: Ważność cech w modelu Gradient Boosting dla średniej oceny
#| echo: false
feature_importance = model.estimators_[0].feature_importances_
feature_names = X_train.columns
for column in ['designers', 'artists', 'publishers']:
    indices = [i for i, feature in enumerate(feature_names) if feature.startswith(column)]
    importance = feature_importance[indices].sum()
    feature_importance = np.delete(feature_importance, indices)
    feature_importance = np.append(feature_importance, importance)
    feature_names = np.delete(feature_names, indices)
    feature_names = np.append(feature_names, column)
feature_importance = np.abs(feature_importance)
feature_importance = feature_importance / feature_importance.sum()
sort = np.argsort(feature_importance)
plt.barh(feature_names[sort], feature_importance[sort])
plt.xlabel('Ważność cech')
plt.title('Ważność cech w modelu Gradient Boosting dla średniej oceny')
plt.gcf().set_figheight(3.5)
plt.show()
```

```{python}
#| label: gradient-boosting-feature-importance-2
#| fig-cap: Ważność cech w modelu Gradient Boosting dla odchylenia standardowego ocen
#| echo: false
feature_importance = model.estimators_[1].feature_importances_
feature_names = X_train.columns
for column in ['designers', 'artists', 'publishers']:
    indices = [i for i, feature in enumerate(feature_names) if feature.startswith(column)]
    importance = feature_importance[indices].sum()
    feature_importance = np.delete(feature_importance, indices)
    feature_importance = np.append(feature_importance, importance)
    feature_names = np.delete(feature_names, indices)
    feature_names = np.append(feature_names, column)
feature_importance = np.abs(feature_importance)
feature_importance = feature_importance / feature_importance.sum()
sort = np.argsort(feature_importance)
plt.barh(feature_names[sort], feature_importance[sort])
plt.xlabel('Ważność cech')
plt.title('Ważność cech w modelu Gradient Boosting dla odchylenia standardowego ocen')
plt.gcf().set_figheight(3.5)
plt.show()
```

### Wnioski

- Model GB uwzględnia złożone i nieliniowe zależności między cechami, co pozwala mu lepiej wykorzystać dane. Dzięki temu cechy takie jak rynek wtórny (`for_trade`, `want_in_trade`) oraz popularność (`page_views`, `owners`) stają się bardziej istotne.
- Regresja liniowa nadmiernie polega na cechach o bezpośrednim wpływie, takich jak liczba projektantów czy artystów, podczas gdy pomija subtelne zależności w&nbsp;danych.
- W regresji liniowej dominują cechy silnie powiązane z jakością twórców (projektanci, artyści), podczas gdy GB lepiej uwzględnia popularność, rynek wtórny oraz nieliniowe relacje między cechami.
- Regresja liniowa może być użyteczna dla prostych interpretacji, podczas gdy Gradient Boosting jest bardziej odpowiedni do analizy złożonych zależności w danych.

# Podsumowanie

Projekt polegał na scrapowaniu danych o grach planszowych z serwisu BoardGameGeek oraz analizie tych danych. Proces scrapowania został zrealizowany za pomocą skryptu w&nbsp;Pythonie, który wykorzystuje bibliotekę Selenium do nawigacji po stronie internetowej i pobierania informacji o grach. Zebrane dane zostały następnie poddane analizie przy użyciu różnych technik analizy danych i uczenia maszynowego.

## Kluczowe wnioski z analizy danych

1. **Oceny gier**: Większość gier planszowych jest dobrze oceniana przez użytkowników, z największą liczbą ocen w przedziale 7-8.
2. **Złożoność gry**: Gry o większej złożoności są lepiej oceniane, co sugeruje, że gracze cenią bardziej skomplikowane i wymagające gry.
3. **Popularność**: Najpopularniejsze gry mają bardzo wysokie oceny, co wskazuje na ich wysoką jakość. Wydawcy tacy jak Fantasy Flight Games dominują na rynku.
4. **Trendy**: W ostatnich latach gry planszowe są coraz lepiej oceniane, co może świadczyć o postępie w tej dziedzinie i rosnącej jakości nowych gier.
5. **Projektanci**: Renoma projektantów, artystów i wydawców ma znaczący wpływ na oceny gier.

## Modelowanie predykcyjne

1. **Regresja liniowa**: Model regresji liniowej wykazał, że cechy związane z twórcami gry mają kluczowe znaczenie dla średniej oceny i odchylenia standardowego ocen.
2. **Gradient Boosting**: Model Gradient Boosting osiągnął lepsze wyniki, uwzględniając złożone i nieliniowe zależności między cechami. Cechy takie jak popularność i rynek wtórny stały się bardziej istotne.

## Wnioski końcowe

Analiza pokazuje, że rynek gier planszowych jest dynamiczny i rozwijający się, z rosnącą jakością gier i dużym zaangażowaniem społeczności graczy. Modele predykcyjne mogą być użyteczne w przewidywaniu ocen gier na podstawie ich cech, co może być cenną wskazówką dla twórców i wydawców gier planszowych.
